// ══════════════════════════════════════════════════════════════
//  PDF generation for hazard sheets & incident reports.
//  Uses jsPDF to build a real PDF file each call (fresh every time —
//  no reused iframe/blob, so it never goes blank on the 2nd+ attempt).
//  Exposes: buildHazardPdf, buildIncidentPdf, sharePdf, printPdf.
// ══════════════════════════════════════════════════════════════
// jsPDF is loaded lazily (only when a PDF is first generated) to keep the
// app's initial load small. Cached after first use.
let _jsPDF = null;
async function getJsPDF() {
  if (!_jsPDF) { const m = await import("jspdf"); _jsPDF = m.jsPDF; }
  return _jsPDF;
}

const GREEN = [45, 74, 34];
const LIME = [141, 198, 63];
const GREY = [110, 110, 110];
const DARK = [20, 33, 10];

// Strip emoji / non-latin so the core PDF font doesn't render tofu boxes.
function clean(s) {
  return String(s == null ? "" : s)
    .replace(/[\u{1F000}-\u{1FFFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}\uFE0F]/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}
// Keep newlines for multi-line fields (control measures), just strip emoji.
function cleanMultiline(s) {
  return String(s == null ? "" : s)
    .replace(/[\u{1F000}-\u{1FFFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}\uFE0F]/gu, "")
    .split("\n").map((l) => l.trim()).filter(Boolean).join("\n");
}

function riskLabel(r) { return r === "high" ? "High" : r === "med" ? "Medium" : "Low"; }
function sevLabel(s) { return s === "high" ? "Serious" : s === "med" ? "Moderate" : "Minor"; }

// Shared header/footer. Returns starting y for body content.
function header(doc, company, title) {
  const M = 40;
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 68, "F");
  doc.setTextColor(...LIME);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(clean(company.name) || "The Treeman", M, 34);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(title, M, 52);
  const contact = [clean(company.phone), clean(company.email)].filter(Boolean).join("   ");
  if (contact) {
    doc.setFontSize(8);
    doc.setTextColor(210, 230, 190);
    doc.text(contact, doc.internal.pageSize.getWidth() - M, 34, { align: "right" });
  }
  return 92;
}

function footer(doc) {
  const h = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GREY);
  doc.text(
    "Generated by The Treeman Field Ops  ·  " + new Date().toLocaleString("en-NZ"),
    doc.internal.pageSize.getWidth() / 2, h - 24, { align: "center" }
  );
}

// Draw a section heading with an underline; returns new y.
function heading(doc, text, y, M) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...DARK);
  doc.text(text, M, y);
  doc.setDrawColor(...LIME);
  doc.setLineWidth(1.5);
  doc.line(M, y + 4, doc.internal.pageSize.getWidth() - M, y + 4);
  return y + 20;
}

// Label: value row (wrapped). Returns new y.
function metaRow(doc, label, value, y, M) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...DARK);
  doc.text(label, M, y);
  doc.setFont("helvetica", "normal");
  const vx = M + 90;
  const maxW = doc.internal.pageSize.getWidth() - vx - M;
  const lines = doc.splitTextToSize(clean(value) || "—", maxW);
  doc.text(lines, vx, y);
  return y + Math.max(16, lines.length * 13);
}

// Page-break helper.
function ensureSpace(doc, y, need, M) {
  if (y + need > doc.internal.pageSize.getHeight() - 40) {
    footer(doc);
    doc.addPage();
    return 50;
  }
  return y;
}

export async function buildHazardPdf(rec, company = {}) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const M = 40;
  const W = doc.internal.pageSize.getWidth();
  let y = header(doc, company, "Site Hazard Sheet");

  y = metaRow(doc, "Site", rec.site, y, M);
  y = metaRow(doc, "Date", rec.date, y, M);
  y = metaRow(doc, "Type of work", rec.jobType, y, M);
  y = metaRow(doc, "Team lead", rec.lead, y, M);
  y = metaRow(doc, "Overall risk", riskLabel(rec.risk), y, M);
  y += 8;

  y = heading(doc, "Identified Hazards & Controls", y, M);

  const hazards = rec.hazards || [];
  const details = rec.hazardDetails || {};
  if (!hazards.length) {
    doc.setFont("helvetica", "italic"); doc.setFontSize(10); doc.setTextColor(...GREY);
    doc.text("No hazards ticked.", M, y); y += 18;
  } else {
    hazards.forEach((h) => {
      const d = details[h] || {};
      const controlLines = doc.splitTextToSize(cleanMultiline(d.control) || "—", W - 2 * M - 12);
      const noteLines = d.notes ? doc.splitTextToSize(cleanMultiline(d.notes), W - 2 * M - 12) : [];
      const blockH = 18 + controlLines.length * 12 + (noteLines.length ? noteLines.length * 12 + 6 : 0) + 12;
      y = ensureSpace(doc, y, blockH, M);
      // hazard name
      doc.setFont("helvetica", "bold"); doc.setFontSize(10.5); doc.setTextColor(...GREEN);
      doc.text(clean(h), M, y); y += 14;
      doc.setTextColor(...DARK);
      doc.setFont("helvetica", "bold"); doc.setFontSize(9);
      doc.text("Control:", M + 6, y);
      doc.setFont("helvetica", "normal");
      doc.text(controlLines, M + 52, y); y += controlLines.length * 12;
      if (noteLines.length) {
        y += 2;
        doc.setFont("helvetica", "bold"); doc.text("Notes:", M + 6, y);
        doc.setFont("helvetica", "normal"); doc.text(noteLines, M + 52, y);
        y += noteLines.length * 12;
      }
      y += 10;
      doc.setDrawColor(225, 225, 225); doc.setLineWidth(0.5);
      doc.line(M, y - 4, W - M, y - 4);
    });
  }

  if (rec.otherHazards) {
    y = ensureSpace(doc, y, 40, M);
    y += 4;
    y = metaRow(doc, "Other hazards", rec.otherHazards, y, M);
  }

  y += 8;
  y = ensureSpace(doc, y, 60, M);
  y = heading(doc, "Team Sign-Off", y, M);
  const signers = rec.signers || [];
  if (!signers.length) {
    doc.setFont("helvetica", "italic"); doc.setFontSize(10); doc.setTextColor(...GREY);
    doc.text("No crew recorded.", M, y); y += 16;
  } else {
    signers.forEach((s) => {
      y = ensureSpace(doc, y, 22, M);
      doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(...DARK);
      doc.text(clean(s.name) + "  (" + (clean(s.role) || "Crew") + ")", M, y);
      doc.setTextColor(...(s.signed ? GREEN : GREY));
      doc.text(s.signed ? "Signed" : "_________________", W - M, y, { align: "right" });
      y += 8;
      doc.setDrawColor(225, 225, 225); doc.setLineWidth(0.5);
      doc.line(M, y, W - M, y); y += 14;
    });
  }

  footer(doc);
  return doc;
}

export async function buildIncidentPdf(rec, company = {}) {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const M = 40;
  let y = header(doc, company, "Incident Report");

  const people = Array.isArray(rec.peopleInvolved)
    ? rec.peopleInvolved.join(", ")
    : (rec.peopleInvolved || rec.personInvolved || "");
  const witnesses = Array.isArray(rec.witnesses) ? rec.witnesses.join(", ") : (rec.witnesses || "");

  y = metaRow(doc, "Type", rec.type, y, M);
  y = metaRow(doc, "When", clean(rec.date) + " " + clean(rec.time), y, M);
  y = metaRow(doc, "Location", rec.site, y, M);
  y = metaRow(doc, "Severity", sevLabel(rec.severity), y, M);
  y = metaRow(doc, "Notifiable", rec.notifiable ? "Yes — potentially notifiable to WorkSafe NZ" : "No", y, M);
  y = metaRow(doc, "Status", rec.status === "closed" ? "Closed" : "Open", y, M);
  y += 8;

  y = heading(doc, "Details", y, M);
  if (people) y = metaRow(doc, "Person(s)", people, y, M);
  if (rec.injuryDetails) y = metaRow(doc, "Injury", rec.injuryDetails, y, M);

  // Long text blocks
  const block = (label, val) => {
    if (!val) return;
    y = ensureSpace(doc, y, 48, M);
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(...DARK);
    doc.text(label, M, y); y += 14;
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(cleanMultiline(val), doc.internal.pageSize.getWidth() - 2 * M);
    doc.text(lines, M, y); y += lines.length * 12 + 8;
  };
  block("What happened", rec.description);
  block("Immediate actions taken", rec.immediateActions);
  if (witnesses) y = metaRow(doc, "Witnesses", witnesses, y, M);

  y += 6;
  y = ensureSpace(doc, y, 50, M);
  y = heading(doc, "Reported By", y, M);
  y = metaRow(doc, "Name", rec.reportedBy, y, M);
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(...DARK);
  doc.text("Signature:", M, y);
  doc.setTextColor(...(rec.signed ? GREEN : GREY));
  doc.text(rec.signed ? "Signed" : "_________________", M + 70, y);

  footer(doc);
  return doc;
}

// Filename-safe slug.
function slug(s) {
  return clean(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "record";
}

export function pdfFilename(kind, rec) {
  const who = kind === "hazard" ? rec.site : rec.type;
  return `treeman-${kind}-${slug(who)}-${rec.date || ""}.pdf`;
}

// Share via the iOS/native share sheet, with a download fallback.
export async function sharePdf(doc, filename) {
  const blob = doc.output("blob");
  const file = new File([blob], filename, { type: "application/pdf" });
  // Try native share with the actual file first (best on iOS Safari).
  if (navigator.canShare && navigator.canShare({ files: [file] })) {
    try {
      await navigator.share({ files: [file], title: filename });
      return "shared";
    } catch (e) {
      if (e && e.name === "AbortError") return "cancelled";
      // fall through to download
    }
  }
  // Fallback: trigger a download of the blob.
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 1500);
  return "downloaded";
}

// Print: open the freshly-built PDF in a hidden iframe and print it.
// A brand-new blob URL + iframe every call means it never goes blank on repeat.
export function printPdf(doc) {
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const existing = document.getElementById("tm-pdf-print-frame");
  if (existing) existing.remove();
  const iframe = document.createElement("iframe");
  iframe.id = "tm-pdf-print-frame";
  iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;visibility:hidden;";
  iframe.onload = () => {
    setTimeout(() => {
      try { iframe.contentWindow.focus(); iframe.contentWindow.print(); }
      catch (e) { /* ignore */ }
      setTimeout(() => {
        const f = document.getElementById("tm-pdf-print-frame");
        if (f) f.remove();
        URL.revokeObjectURL(url);
      }, 1500);
    }, 400);
  };
  iframe.src = url;
  document.body.appendChild(iframe);
}
